faiss_db:
  collection_name: "document_portal_collection"


embedding_model:
  transformer:
    provider: "huggingface"
    model_name: "all-MiniLM-L6-v2"

  openai:
    provider: "openai"
    model_name: "text-embedding-ada-002"

  azure_openai:
    provider: "azure_openai"
    model_name: "text-embedding-ada-002"
  
  google:
    provider: "google"
    model_name: "models/gemini-embedding-001"

retrieval:
  top_k: 10


llm:
  groq:
    provider: "groq"
    model_name: "llama-3.3-70b-versatile"
    temperature: 0
    max_tokens: 2048
  
  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_tokens: 2048

  openai:
    provider: "openai"
    model_name: "gpt-4"
    temperature: 0.7
    max_tokens: 2048

  azure_openai:
    provider: "azure_openai"
    model_name: "gpt-4"
    temperature: 0.7
    max_tokens: 2048