name: Deploy to Amazon ECS

on:
  push:
    branches:
      - "master"

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: documentportal
  ECS_SERVICE: document-portal-service
  ECS_CLUSTER: document-portal-cluster
  ECS_TASK_DEFINATION: .github/workflows/task_defination.json
  CONTAINER_NAME: document-portal-container

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    enviroment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3   # copy code on github runner machine from github repository

    - name: Configure AWS credentials
      uses: aws-action/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secret.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: $ {{env.AWS_REGION}}

    - name: Deploy ECR stack (optional)
      run: |
        aws cloudformation deploy \
        --template-file .github/workflows/template.yml \
        --stack-name ecr-repo-stack \
        --regin ${{ env.AWS_REGION}} \
        --capbilities CAPABILITY_NAMED_IAM
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env: 
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry}}
        IMAGE_TAG: ${{ github.sha }}
      run: |
       IMAGE_URI=${{steps.login-ecr.outputs.registry}}
       docker build -t $IMAGE_URI .
       docker push $IMAGE_URI
       echo "image=$IMAGE_URI" >> $GITHUB_OUTPUT

    - name: Fill in the new image ID in the Amazon ECS task definition
      id : task_def
      uses: aws-action/amazon-ecs-render-task-defination@v1
      with:
        task-defination: ${{ env.ECS_TASK_DEFINATION }}
        container-name: ${{env.CONTAINER_NAME}}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task defination
      uses: aws-actions/amazon-ecs-deploy-task-defination@v1
      with: 
        task-defination: ${{steps.task_def.outputs.task_defination }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

    - name: Deployment Success Message
      run: echo "Deployment Successful! App is live on ECS Fargate"




    


